wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1638715624
    t:
      1:
      - 1
      3:
      - 13
      - 16
      4: 3.8.3
      5: 0.12.7
      8:
      - 5
algo_name:
  desc: null
  value: PPO
anneal_lr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 2048
clip_coef:
  desc: null
  value: 0.2
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: HalfCheetahBulletEnv-v0
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
lr:
  desc: null
  value: 0.0003
max_grad_norm:
  desc: null
  value: 0.5
max_timesteps:
  desc: null
  value: 2000000
minibatch_size:
  desc: null
  value: 64
n_minibatch:
  desc: null
  value: 32
num_envs:
  desc: null
  value: 1
num_timesteps_per_env:
  desc: null
  value: 2048
save_model:
  desc: null
  value: true
seed:
  desc: null
  value: 1
target_kl:
  desc: null
  value: 0.03
update_epochs:
  desc: null
  value: 10
vf_coef:
  desc: null
  value: 0.5
